require 'joestar.plugins.which-key'
-- require("joestar.plugins.conform")
require 'joestar.plugins.telescope'
require 'joestar.plugins.catppuccin'
require 'joestar.plugins.lualine'
require 'joestar.plugins.42header'
require 'joestar.plugins.presence'
require 'joestar.plugins.treesitter'
-- require 'joestar.plugins.tmux'
-- require 'joestar.plugins.lsp'
