require 'joestar.plugins.which-key'
require 'joestar.plugins.telescope'
require 'joestar.plugins.lualine'
require 'joestar.plugins.42header'
require 'joestar.plugins.presence'
require 'joestar.plugins.treesitter'
require 'joestar.plugins.vimade'
require 'joestar.plugins.kanagawa'
require 'joestar.plugins.colorizer'
-- require 'joestar.plugins.devcontainer'
-- require 'joestar.plugins.smear_cursor'
-- require 'joestar.plugins.neoscroll'
-- require 'joestar.plugins.tmux'
-- require 'joestar.plugins.lsp'
-- require 'joestar.plugins.conform'
-- require 'joestar.plugins.catppuccin'
